# Generated by Django 4.2.16 on 2025-11-13 01:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthcareProvider",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Faux = suppression logique pour conformité RGPD",
                        verbose_name="active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ligne1",
                    models.CharField(
                        help_text="Rue, numéro, bâtiment",
                        max_length=255,
                        verbose_name="address line 1",
                    ),
                ),
                (
                    "ligne2",
                    models.CharField(
                        blank=True,
                        help_text="Complément d'adresse (optionnel)",
                        max_length=255,
                        verbose_name="address line 2",
                    ),
                ),
                (
                    "ville",
                    models.CharField(
                        help_text="Ville", max_length=100, verbose_name="city"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        help_text="Région administrative",
                        max_length=100,
                        verbose_name="region",
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True,
                        help_text="Code postal",
                        max_length=20,
                        verbose_name="postal code",
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Sénégal",
                        help_text="Pays",
                        max_length=100,
                        verbose_name="country",
                    ),
                ),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude GPS",
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude GPS",
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom de l'établissement",
                        max_length=200,
                        verbose_name="name",
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hôpital"),
                            ("clinic", "Clinique"),
                            ("medical_center", "Centre Médical"),
                            ("pharmacy", "Pharmacie"),
                            ("laboratory", "Laboratoire"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="provider type",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Numéro d'agrément officiel",
                        max_length=50,
                        unique=True,
                        verbose_name="registration number",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        help_text="Numéro de licence d'exploitation",
                        max_length=50,
                        verbose_name="license number",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "opening_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Horaires d'ouverture par jour",
                        verbose_name="opening hours",
                    ),
                ),
                (
                    "specialties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Spécialités médicales disponibles",
                        verbose_name="specialties",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Services proposés",
                        verbose_name="services",
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                        verbose_name="rating",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="review count"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Prestataire vérifié par l'administration",
                        verbose_name="is verified",
                    ),
                ),
                (
                    "is_accepting_patients",
                    models.BooleanField(
                        default=True, verbose_name="is accepting patients"
                    ),
                ),
                (
                    "is_cmu_partner",
                    models.BooleanField(
                        default=False,
                        help_text="Conventionné avec la CMU",
                        verbose_name="is CMU partner",
                    ),
                ),
                (
                    "cmu_contract_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="CMU contract number"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Compte utilisateur du prestataire",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="healthcare_provider",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Healthcare Provider",
                "verbose_name_plural": "Healthcare Providers",
                "db_table": "healthcare_providers",
            },
        ),
        migrations.CreateModel(
            name="HealthTicket",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Faux = suppression logique pour conformité RGPD",
                        verbose_name="active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        db_index=True,
                        help_text="Numéro unique du billet (ex: TS-2024-001234)",
                        max_length=20,
                        unique=True,
                        verbose_name="ticket number",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateTimeField(
                        help_text="Date et heure du rendez-vous",
                        verbose_name="appointment date",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        help_text="Spécialité médicale",
                        max_length=100,
                        verbose_name="specialty",
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("general", "Consultation générale"),
                            ("specialist", "Consultation spécialisée"),
                            ("followup", "Suivi"),
                            ("emergency", "Urgence"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="consultation type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Créé"),
                            ("pending_payment", "En attente de paiement"),
                            ("paid", "Payé"),
                            ("checked_in", "Enregistré à l'accueil"),
                            ("in_consultation", "En consultation"),
                            ("consultation_completed", "Consultation terminée"),
                            ("prescription_issued", "Ordonnance émise"),
                            ("completed", "Terminé"),
                            ("cancelled", "Annulé"),
                            ("refunded", "Remboursé"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=30,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("emergency", "Urgence"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Motif de consultation",
                        verbose_name="reason for visit",
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True,
                        help_text="Symptômes décrits par le patient",
                        verbose_name="symptoms",
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="consultation fee",
                    ),
                ),
                (
                    "cmu_coverage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant pris en charge par la CMU",
                        max_digits=10,
                        verbose_name="CMU coverage",
                    ),
                ),
                (
                    "patient_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant payé par le patient",
                        max_digits=10,
                        verbose_name="patient payment",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="QR code pour vérification rapide",
                        upload_to="health_tickets/qr_codes/",
                        verbose_name="QR code",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="checked in at"
                    ),
                ),
                (
                    "consultation_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="consultation started at"
                    ),
                ),
                (
                    "consultation_ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="consultation ended at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="cancellation reason"),
                ),
                (
                    "staff_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes internes du personnel médical",
                        verbose_name="staff notes",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Médecin traitant",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient bénéficiaire",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_tickets",
                        to="wallet.transaction",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Prestataire de santé",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_tickets",
                        to="healthcare.healthcareprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Ticket",
                "verbose_name_plural": "Health Tickets",
                "db_table": "health_tickets",
                "ordering": ["-appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Faux = suppression logique pour conformité RGPD",
                        verbose_name="active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consultation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="consultation date",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        help_text="Motif principal de consultation",
                        verbose_name="chief complaint",
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="temperature (°C)",
                    ),
                ),
                (
                    "blood_pressure_systolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="blood pressure systolic"
                    ),
                ),
                (
                    "blood_pressure_diastolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="blood pressure diastolic"
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="heart rate (bpm)"
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="respiratory rate"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="weight (kg)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="height (cm)",
                    ),
                ),
                (
                    "physical_examination",
                    models.TextField(blank=True, verbose_name="physical examination"),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        help_text="Diagnostic médical", verbose_name="diagnosis"
                    ),
                ),
                (
                    "treatment_plan",
                    models.TextField(
                        help_text="Plan de traitement", verbose_name="treatment plan"
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(blank=True, verbose_name="clinical notes"),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="follow-up required"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="follow-up date"
                    ),
                ),
                (
                    "follow_up_instructions",
                    models.TextField(blank=True, verbose_name="follow-up instructions"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to="healthcare.healthticket",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medical_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record",
                "verbose_name_plural": "Medical Records",
                "db_table": "medical_records",
                "ordering": ["-consultation_date"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Faux = suppression logique pour conformité RGPD",
                        verbose_name="active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prescription_number",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="prescription number",
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="issue date"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        help_text="Date d'expiration de l'ordonnance",
                        verbose_name="expiry date",
                    ),
                ),
                (
                    "is_dispensed",
                    models.BooleanField(
                        default=False,
                        help_text="Médicaments délivrés en pharmacie",
                        verbose_name="is dispensed",
                    ),
                ),
                (
                    "dispensed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="dispensed at"
                    ),
                ),
                (
                    "dispensed_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom de la pharmacie ayant délivré l'ordonnance",
                        max_length=200,
                        verbose_name="dispensed by pharmacy",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        upload_to="prescriptions/qr_codes/",
                        verbose_name="QR code",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "health_ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="healthcare.healthticket",
                    ),
                ),
                (
                    "medical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="healthcare.medicalrecord",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription",
                "verbose_name_plural": "Prescriptions",
                "db_table": "prescriptions",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionMedication",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Faux = suppression logique pour conformité RGPD",
                        verbose_name="active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=200, verbose_name="medication name"),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text="ex: 500mg", max_length=100, verbose_name="dosage"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="ex: 2 fois par jour",
                        max_length=200,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="ex: 7 jours", max_length=100, verbose_name="duration"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Nombre de boîtes/flacons", verbose_name="quantity"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Instructions spécifiques",
                        verbose_name="instructions",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="healthcare.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prescription Medication",
                "verbose_name_plural": "Prescription Medications",
                "db_table": "prescription_medications",
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["prescription_number"], name="prescriptio_prescri_b8a9ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "-issue_date"], name="prescriptio_patient_c57007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["is_dispensed"], name="prescriptio_is_disp_9780d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["patient", "-consultation_date"],
                name="medical_rec_patient_28139c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["health_ticket"], name="medical_rec_health__bf8a03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["doctor"], name="medical_rec_doctor__1ae353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthticket",
            index=models.Index(
                fields=["ticket_number"], name="health_tick_ticket__54c5fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthticket",
            index=models.Index(
                fields=["patient", "status"], name="health_tick_patient_eb15c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthticket",
            index=models.Index(
                fields=["provider", "appointment_date"],
                name="health_tick_provide_53399e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthticket",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="health_tick_status_15001b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthticket",
            index=models.Index(
                fields=["priority"], name="health_tick_priorit_4a9999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthcareprovider",
            index=models.Index(
                fields=["provider_type", "is_verified"],
                name="healthcare__provide_428bbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthcareprovider",
            index=models.Index(
                fields=["is_cmu_partner"], name="healthcare__is_cmu__fe4f83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthcareprovider",
            index=models.Index(fields=["rating"], name="healthcare__rating_1137bc_idx"),
        ),
    ]
