# Generated by Django 4.2.16 on 2025-11-12 22:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("READ", "Lecture"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("ACCESS", "Accès"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("PERMISSION_CHANGE", "Changement de permissions"),
                        ],
                        db_index=True,
                        help_text="Type d'action effectuée",
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type de ressource (Transaction, MedicalRecord, etc.)",
                        max_length=100,
                        verbose_name="resource type",
                    ),
                ),
                (
                    "resource_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID de la ressource concernée",
                        verbose_name="resource ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Adresse IP de l'utilisateur",
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent du navigateur",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Détails des modifications (avant/après)",
                        verbose_name="changes",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métadonnées additionnelles",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash de l'entrée précédente pour chaînage",
                        max_length=64,
                        verbose_name="previous hash",
                    ),
                ),
                (
                    "current_hash",
                    models.CharField(
                        editable=False,
                        help_text="Hash de cette entrée",
                        max_length=64,
                        unique=True,
                        verbose_name="current hash",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
