# Generated by Django 4.2.16 on 2025-11-12 22:16

import apps.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Adresse email unique pour connexion",
                        max_length=254,
                        unique=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Prénom", max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Nom de famille",
                        max_length=150,
                        verbose_name="last name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Numéro de téléphone sénégalais (+221XXXXXXXXX)",
                        max_length=20,
                        unique=True,
                        validators=[apps.core.validators.validate_senegal_phone],
                        verbose_name="phone number",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Date de naissance (18+ ans requis)",
                        null=True,
                        validators=[apps.core.validators.validate_age],
                        verbose_name="date of birth",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("beneficiary", "Bénéficiaire (Patient)"),
                            ("sponsor", "Souscripteur/Parrain (Diaspora)"),
                            ("healthcare_provider", "Établissement de Santé"),
                            ("pharmacist", "Pharmacien"),
                            ("cmu_agent", "Agent CMU/Mutuelle"),
                            ("admin", "Administrateur Système"),
                        ],
                        db_index=True,
                        help_text="Rôle de l'utilisateur dans le système",
                        max_length=30,
                        verbose_name="user type",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Email vérifié",
                        verbose_name="email verified",
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="email verified at"
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Téléphone vérifié",
                        verbose_name="phone verified",
                    ),
                ),
                (
                    "phone_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="phone verified at"
                    ),
                ),
                (
                    "kyc_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Vérification d'identité complétée",
                        verbose_name="KYC verified",
                    ),
                ),
                (
                    "kyc_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="KYC verified at"
                    ),
                ),
                (
                    "kyc_level",
                    models.IntegerField(
                        choices=[
                            (0, "Non vérifié"),
                            (1, "Basique"),
                            (2, "Complet"),
                            (3, "Avancé"),
                        ],
                        default=0,
                        help_text="Niveau de vérification KYC",
                        verbose_name="KYC level",
                    ),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Authentification à deux facteurs activée",
                        verbose_name="MFA enabled",
                    ),
                ),
                (
                    "mfa_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret TOTP pour MFA",
                        max_length=32,
                        verbose_name="MFA secret",
                    ),
                ),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Codes de secours MFA",
                        verbose_name="backup codes",
                    ),
                ),
                (
                    "failed_login_attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre de tentatives de connexion échouées",
                        verbose_name="failed login attempts",
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de fin de verrouillage du compte",
                        null=True,
                        verbose_name="locked until",
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Dernière adresse IP de connexion",
                        null=True,
                        verbose_name="last login IP",
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date du dernier changement de mot de passe",
                        null=True,
                        verbose_name="password changed at",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Photo de profil",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="avatar",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Biographie courte",
                        max_length=500,
                        verbose_name="bio",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("wo", "Wolof"),
                        ],
                        default="fr",
                        help_text="Langue préférée",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Dakar",
                        help_text="Fuseau horaire",
                        max_length=50,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Processus d'onboarding terminé",
                        verbose_name="onboarding completed",
                    ),
                ),
                (
                    "terms_accepted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'acceptation des CGU",
                        null=True,
                        verbose_name="terms accepted at",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Faux = suppression logique pour conformité RGPD",
                        verbose_name="active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nin",
                    models.CharField(
                        blank=True,
                        help_text="Numéro d'Identification National (13 chiffres)",
                        max_length=13,
                        null=True,
                        unique=True,
                        validators=[apps.core.validators.validate_nin],
                        verbose_name="NIN",
                    ),
                ),
                (
                    "cmu_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Numéro d'adhérent CMU",
                        max_length=50,
                        verbose_name="CMU number",
                    ),
                ),
                (
                    "cmu_status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("pending", "En attente"),
                            ("suspended", "Suspendu"),
                        ],
                        default="inactive",
                        help_text="Statut de l'adhésion CMU",
                        max_length=20,
                        verbose_name="CMU status",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        help_text="Groupe sanguin (A+, B-, etc.)",
                        max_length=5,
                        validators=[apps.core.validators.validate_blood_type],
                        verbose_name="blood type",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Poids en kg",
                        max_digits=5,
                        null=True,
                        verbose_name="weight",
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True,
                        help_text="Taille en cm",
                        null=True,
                        verbose_name="height",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Liste des allergies connues",
                        verbose_name="allergies",
                    ),
                ),
                (
                    "medical_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Antécédents médicaux",
                        verbose_name="medical history",
                    ),
                ),
                (
                    "emergency_contacts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Contacts d'urgence [{name, phone, relation}]",
                        verbose_name="emergency contacts",
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=100, verbose_name="region"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Sénégal", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True, verbose_name="notifications enabled"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="email notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=True, verbose_name="SMS notifications"),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="push notifications"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="email"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "success",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="success"
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_credentials", "Invalid Credentials"),
                            ("account_locked", "Account Locked"),
                            ("account_inactive", "Account Inactive"),
                            ("email_not_verified", "Email Not Verified"),
                            ("mfa_required", "MFA Required"),
                            ("mfa_failed", "MFA Failed"),
                        ],
                        max_length=100,
                        verbose_name="failure reason",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Attempt",
                "verbose_name_plural": "Login Attempts",
                "db_table": "login_attempts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "success", "-created_at"],
                        name="login_attem_email_0ec565_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="login_attem_ip_addr_d06a3f_idx",
                    ),
                    models.Index(
                        fields=["success", "-created_at"],
                        name="login_attem_success_7bdd9d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Verification"),
                            ("phone", "Phone Verification"),
                            ("password_reset", "Password Reset"),
                            ("mfa_setup", "MFA Setup"),
                        ],
                        max_length=20,
                        verbose_name="code type",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code de vérification (6 chiffres)",
                        max_length=10,
                        verbose_name="code",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="is used")),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="used at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Date d'expiration du code", verbose_name="expires at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Code",
                "verbose_name_plural": "Verification Codes",
                "db_table": "verification_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code_type", "is_used"],
                        name="verificatio_user_id_77ae8e_idx",
                    ),
                    models.Index(
                        fields=["code", "is_used"], name="verificatio_code_475c0c_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="verificatio_expires_bef114_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True,
                        max_length=40,
                        unique=True,
                        verbose_name="session key",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                        verbose_name="device type",
                    ),
                ),
                (
                    "browser",
                    models.CharField(blank=True, max_length=50, verbose_name="browser"),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="operating system"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="last activity"),
                ),
                (
                    "logged_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="logged out at"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "db_table": "user_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_sessio_user_id_bb1b83_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="user_sessio_session_cc84b9_idx"
                    ),
                    models.Index(
                        fields=["last_activity"], name="user_sessio_last_ac_7cb421_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KYCDocument",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de création automatique",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date et heure de dernière modification",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Faux = suppression logique pour conformité RGPD",
                        verbose_name="active",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de suppression logique",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique UUID4 pour sécurité",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "Carte d'Identité Nationale"),
                            ("passport", "Passeport"),
                            ("driver_license", "Permis de Conduire"),
                            ("residence_permit", "Carte de Séjour"),
                            ("utility_bill", "Facture de Services Publics"),
                            ("selfie", "Photo Selfie avec Document"),
                        ],
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Numéro du document",
                        max_length=100,
                        verbose_name="document number",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        help_text="Fichier du document (PDF, JPG, PNG)",
                        upload_to="kyc_documents/%Y/%m/",
                        verbose_name="document file",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("under_review", "En cours de vérification"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("expired", "Expiré"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verified at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Raison du rejet si applicable",
                        verbose_name="rejection reason",
                    ),
                ),
                (
                    "expires_at",
                    models.DateField(
                        blank=True,
                        help_text="Date d'expiration du document",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes internes pour la vérification",
                        verbose_name="notes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type__in": ["admin", "cmu_agent"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "KYC Document",
                "verbose_name_plural": "KYC Documents",
                "db_table": "kyc_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="kyc_documen_user_id_19faeb_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="kyc_documen_status_d38120_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="users_phone_af6883_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email_verified", "phone_verified"],
                name="users_email_v_56af83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["kyc_verified"], name="users_kyc_ver_e55fff_idx"
            ),
        ),
    ]
